"""
visualization.py — Visualization Module

Handles:
  - Saving matplotlib figures generated by the executor
  - Auto-generating charts from result DataFrames (fallback)
  - Selecting chart type based on data characteristics
  - Consistent premium styling
"""

import io
from pathlib import Path
from typing import Any, Optional

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from utils import get_logger, CHARTS_DIR, safe_filename

log = get_logger("visualization")


# ──────────────────────────────────────────────
# 1. Styling
# ──────────────────────────────────────────────

COLORS = [
    "#4E79A7", "#F28E2B", "#E15759", "#76B7B2",
    "#59A14F", "#EDC948", "#B07AA1", "#FF9DA7",
    "#9C755F", "#BAB0AC",
]


def apply_style():
    """Apply consistent premium chart styling."""
    try:
        plt.style.use("seaborn-v0_8-darkgrid")
    except OSError:
        try:
            plt.style.use("seaborn-darkgrid")
        except OSError:
            plt.style.use("ggplot")

    plt.rcParams.update({
        "figure.facecolor": "#FAFAFA",
        "axes.facecolor": "#FAFAFA",
        "axes.edgecolor": "#CCCCCC",
        "axes.labelsize": 12,
        "axes.titlesize": 14,
        "axes.titleweight": "bold",
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "legend.fontsize": 10,
        "font.family": "sans-serif",
        "font.sans-serif": ["Segoe UI", "Arial", "DejaVu Sans"],
    })


# ──────────────────────────────────────────────
# 2. Save Figure
# ──────────────────────────────────────────────

def save_figure(fig: plt.Figure, name: str = "chart", dpi: int = 150) -> Path:
    """Save a matplotlib figure to the charts directory."""
    filename = safe_filename(name) + ".png"
    path = CHARTS_DIR / filename
    fig.savefig(path, dpi=dpi, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)
    log.info("Chart saved: %s", path)
    return path


# ──────────────────────────────────────────────
# 3. Auto-Detect Chart Type
# ──────────────────────────────────────────────

def _detect_chart_type(result: Any, chart_config: dict) -> str:
    """Determine the best chart type from the data and plan config."""
    explicit = chart_config.get("type", "none")
    if explicit and explicit != "none":
        return explicit

    if isinstance(result, (int, float)):
        return "none"

    if isinstance(result, pd.Series):
        return "bar" if len(result) <= 12 else "line"

    if isinstance(result, pd.DataFrame):
        rows, cols = result.shape
        if rows <= 1:
            return "none"
        return "bar" if rows <= 15 else "line"

    return "none"


# ──────────────────────────────────────────────
# 4. Fallback Chart Generation
# ──────────────────────────────────────────────

def generate_fallback_chart(
    result: Any,
    chart_config: dict,
    plan_title: str = "Analysis",
) -> Optional[plt.Figure]:
    """Generate a chart from the result when the executor didn't produce one."""
    chart_type = _detect_chart_type(result, chart_config)
    if chart_type == "none":
        return None

    apply_style()

    title = chart_config.get("title", plan_title)
    xlabel = chart_config.get("xlabel", "")
    ylabel = chart_config.get("ylabel", "")

    # Convert Series for uniform handling
    if isinstance(result, pd.Series):
        plot_df = result.reset_index()
        plot_df.columns = [xlabel or "Category", ylabel or "Value"]
    elif isinstance(result, pd.DataFrame):
        plot_df = result.copy()
    else:
        return None

    fig, ax = plt.subplots(figsize=(12, 6))

    try:
        if chart_type == "line":
            _plot_line(ax, plot_df)
        elif chart_type == "bar":
            _plot_bar(ax, plot_df)
        elif chart_type == "horizontal_bar":
            _plot_hbar(ax, plot_df)
        elif chart_type == "pie":
            _plot_pie(ax, plot_df)
        elif chart_type == "histogram":
            _plot_histogram(ax, plot_df)
        elif chart_type == "scatter":
            _plot_scatter(ax, plot_df)
        else:
            _plot_bar(ax, plot_df)

        ax.set_title(title, pad=15)
        if chart_type not in ("pie",):
            if xlabel:
                ax.set_xlabel(xlabel)
            if ylabel:
                ax.set_ylabel(ylabel)
        plt.tight_layout()
        return fig

    except Exception as exc:
        log.warning("Fallback chart generation failed: %s", exc)
        plt.close(fig)
        return None


# ──────────────────────────────────────────────
# 5. Chart Plotting Helpers
# ──────────────────────────────────────────────

def _plot_line(ax, df: pd.DataFrame):
    cols = df.columns.tolist()
    x_col, y_cols = cols[0], cols[1:]
    for i, yc in enumerate(y_cols):
        ax.plot(df[x_col], df[yc], marker="o", markersize=4,
                color=COLORS[i % len(COLORS)], linewidth=2, label=yc)
    ax.tick_params(axis="x", rotation=45)
    if len(y_cols) > 1:
        ax.legend()


def _plot_bar(ax, df: pd.DataFrame):
    cols = df.columns.tolist()
    x_col, y_cols = cols[0], cols[1:]
    x = range(len(df))
    width = 0.8 / max(len(y_cols), 1)
    for i, yc in enumerate(y_cols):
        offset = (i - len(y_cols) / 2 + 0.5) * width
        bars = ax.bar([xi + offset for xi in x], df[yc],
                      width=width, color=COLORS[i % len(COLORS)], label=yc)
        for bar in bars:
            h = bar.get_height()
            if h != 0:
                ax.text(bar.get_x() + bar.get_width() / 2, h,
                        f"{h:,.0f}", ha="center", va="bottom", fontsize=8)
    ax.set_xticks(list(x))
    ax.set_xticklabels(df[x_col].astype(str), rotation=45, ha="right")
    if len(y_cols) > 1:
        ax.legend()


def _plot_hbar(ax, df: pd.DataFrame):
    cols = df.columns.tolist()
    x_col, y_col = cols[0], cols[1]
    ax.barh(df[x_col].astype(str), df[y_col], color=COLORS[:len(df)])
    for i, (val, name) in enumerate(zip(df[y_col], df[x_col])):
        ax.text(val, i, f"  {val:,.0f}", va="center", fontsize=9)


def _plot_pie(ax, df: pd.DataFrame):
    cols = df.columns.tolist()
    labels = df[cols[0]].astype(str)
    values = df[cols[1]]
    ax.pie(values, labels=labels, colors=COLORS[:len(df)],
           autopct="%1.1f%%", startangle=140)
    ax.axis("equal")


def _plot_histogram(ax, df: pd.DataFrame):
    cols = df.columns.tolist()
    ax.hist(df[cols[-1]].dropna(), bins=30, color=COLORS[0],
            edgecolor="white", alpha=0.85)


def _plot_scatter(ax, df: pd.DataFrame):
    cols = df.columns.tolist()
    if len(cols) >= 2:
        ax.scatter(df[cols[0]], df[cols[1]], color=COLORS[0],
                   alpha=0.6, edgecolors="white", s=40)


# ──────────────────────────────────────────────
# 6. Export for Streamlit (bytes)
# ──────────────────────────────────────────────

def fig_to_bytes(fig: plt.Figure, fmt: str = "png") -> bytes:
    """Convert a matplotlib figure to bytes."""
    buf = io.BytesIO()
    fig.savefig(buf, format=fmt, dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    buf.seek(0)
    return buf.read()
